v3.87

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX CPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA DEPEND FOUND_AALIB FOUND_ALSA FOUND_DV FOUND_LQT FOUND_MOTIF FOUND_OS FOUND_X11 FOUND_GL FOUND_ZVBI EGREP DLFLAGS LIBPTHREAD LIBOSS LIBCURSES X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS x_includes x_libraries ATHENA FSLIB SUBS TOOLS LDLIBS LIBALSA LIRC LIBZVBI AALIBS LIBDV QTLIBS LIBGL VERSION x11conf resdir USE_MMX LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX CPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA DEPEND FOUND_AALIB FOUND_ALSA FOUND_DV FOUND_LQT FOUND_MOTIF FOUND_OS FOUND_X11 FOUND_GL FOUND_ZVBI EGREP DLFLAGS LIBPTHREAD LIBOSS LIBCURSES X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS x_includes x_libraries ATHENA FSLIB SUBS TOOLS LDLIBS XFT_FLAGS XFT_LIBS LIBALSA LIRC LIBZVBI AALIBS LIBDV QTLIBS LIBGL VERSION x11conf resdir USE_MMX LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -862,6 +862,7 @@ Optional Features:
   --enable-gl             enable opengl support
   --enable-dv             enable dvlib support
   --enable-mmx            enable mmx support
+  --enable-xft            enable xft support
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1343,6 +1344,11 @@ fi;
 # Check whether --enable-mmx or --disable-mmx was given.
 if test "${enable_mmx+set}" = set; then
   enableval="$enable_mmx"
+
+fi;
+# Check whether --enable-xft or --disable-xft was given.
+if test "${enable_xft+set}" = set; then
+  enableval="$enable_xft"
 
 fi;
 
@@ -5031,10 +5037,32 @@ if test "$no_x" != "yes"; then
   FOUND_X11="yes"
   ATHENA="-lXaw -lXmu -lXt $X_PRE_LIBS -lXpm -lXext -lX11 $X_EXTRA_LIBS"
   FSLIB="-lFS"
+  XFT_FLAGS=""
+  XFT_LIBS=""
+  if test "$enable_xft" != "no"; then
+    echo "$as_me:$LINENO: checking for Xft" >&5
+echo $ECHO_N "checking for Xft... $ECHO_C" >&6
+    if test -x "`which pkg-config 2>/dev/null`" && pkg-config xft; then
+      XFT_FLAGS="`pkg-config --cflags xft`"
+      XFT_LIBS="`pkg-config --libs xft`"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_XFT 1
+_ACEOF
+
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    else
+      echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    fi
+  fi
 else
   ATHENA=""
   FSLIB=""
 fi
+
+
 
 
 
@@ -5848,6 +5876,134 @@ if test $ac_cv_lib_Xinerama_XineramaQueryExtension = yes; then
 _ACEOF
 
   LIBS="-lXinerama $LIBS"
+
+fi
+
+
+echo "$as_me:$LINENO: checking for XRenderQueryExtension in -lXrender" >&5
+echo $ECHO_N "checking for XRenderQueryExtension in -lXrender... $ECHO_C" >&6
+if test "${ac_cv_lib_Xrender_XRenderQueryExtension+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lXrender $X_LIBS $X_PRE_LIBS -lXext -lX11 $X_EXTRA_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char XRenderQueryExtension ();
+int
+main ()
+{
+XRenderQueryExtension ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Xrender_XRenderQueryExtension=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_Xrender_XRenderQueryExtension=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_Xrender_XRenderQueryExtension" >&5
+echo "${ECHO_T}$ac_cv_lib_Xrender_XRenderQueryExtension" >&6
+if test $ac_cv_lib_Xrender_XRenderQueryExtension = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBXRENDER 1
+_ACEOF
+
+  LIBS="-lXrender $LIBS"
+
+fi
+
+
+echo "$as_me:$LINENO: checking for XRRConfigCurrentConfiguration in -lXrandr" >&5
+echo $ECHO_N "checking for XRRConfigCurrentConfiguration in -lXrandr... $ECHO_C" >&6
+if test "${ac_cv_lib_Xrandr_XRRConfigCurrentConfiguration+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lXrandr $X_LIBS $X_PRE_LIBS -lXext -lX11 $X_EXTRA_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char XRRConfigCurrentConfiguration ();
+int
+main ()
+{
+XRRConfigCurrentConfiguration ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_Xrandr_XRRConfigCurrentConfiguration=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_Xrandr_XRRConfigCurrentConfiguration=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_Xrandr_XRRConfigCurrentConfiguration" >&5
+echo "${ECHO_T}$ac_cv_lib_Xrandr_XRRConfigCurrentConfiguration" >&6
+if test $ac_cv_lib_Xrandr_XRRConfigCurrentConfiguration = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBXRANDR 1
+_ACEOF
+
+  LIBS="-lXrandr $LIBS"
 
 fi
 
@@ -6755,6 +6911,8 @@ s,@FSLIB@,$FSLIB,;t t
 s,@SUBS@,$SUBS,;t t
 s,@TOOLS@,$TOOLS,;t t
 s,@LDLIBS@,$LDLIBS,;t t
+s,@XFT_FLAGS@,$XFT_FLAGS,;t t
+s,@XFT_LIBS@,$XFT_LIBS,;t t
 s,@LIBALSA@,$LIBALSA,;t t
 s,@LIRC@,$LIRC,;t t
 s,@LIBZVBI@,$LIBZVBI,;t t
